"""Offline, dependency-free HTML report. Open reports/dashboard.html."""
import json
from pathlib import Path

def build(out):
    out=Path(out)
    payload=json.dumps({'results':json.loads((out/'results.json').read_text()),'examples':json.loads((out/'explanations.json').read_text())}).replace('<','\\u003c')
    html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FairFreeze review desk</title><style>
body{margin:0;background:#0b1420;color:#e7edf5;font:16px system-ui}main{max-width:1100px;margin:auto;padding:36px}h1{font-size:42px;margin-bottom:8px}p{line-height:1.6;color:#aebfd0}.card{background:#152334;border:1px solid #2c4055;border-radius:12px;padding:24px;margin:20px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #304158;padding:12px}select,button{font:inherit;padding:10px;background:#253b51;color:white;border:1px solid #58718a;border-radius:6px}.bar{height:12px;border-radius:3px;background:#48c5a5;display:inline-block}small{color:#b4c3d3}img{max-width:100%;background:white;border-radius:8px}.scroll{overflow:auto}strong{color:#69ddc1}</style><main><small>FRAUD CHAIN RESEARCH · SYNTHETIC DATA</small><h1>FairFreeze</h1><p>Rank accounts for investigation. Review the evidence behind each score. Any hold requires an independently verified complaint, fund tracing and authorized human decision.</p><div class="card"><h2>Chain-held-out evaluation</h2><p id="summary"></p><div class="scroll"><table id="metrics"></table></div><p>Thresholds are selected inside training folds at an exploratory 80% precision target. Outer-fold precision may be lower. Scores are uncalibrated; top-k scores from different fold models are diagnostic.</p></div><div class="card"><h2>Account evidence</h2><select id="account"></select><div id="details"></div><button id="download">Download evidence JSON</button></div><div class="card"><h2>Precision–recall</h2><img src="precision_recall.png" alt="Precision recall curves"><p>Feature selection previously used the original chain. Full-graph features assume the entire transaction snapshot is available at scoring time. This is not a prospective temporal evaluation.</p></div><div class="card"><h2>Amount sensitivity</h2><div id="sensitivity"></div><p>These interventions modify aggregate amount features while holding graph and flow features fixed. They are sensitivity probes, not realistic generator stress tests.</p></div></main><script>const data=PAYLOAD;
const el=id=>document.getElementById(id);const fmt=v=>v===null?'Unavailable':(100*v).toFixed(1)+'%';
el('summary').textContent=`${data.results.accounts.toLocaleString()} accounts · ${data.results.positives} labeled positives · ${data.results.chain_components} independent chain groups`;
el('metrics').innerHTML='<tr><th>Model</th><th>Mean AP</th><th>Precision</th><th>Recall</th><th>Flagged</th><th>False positives</th></tr>'+Object.entries(data.results.metrics).map(([n,m])=>`<tr><td>${n}</td><td>${m.mean_fold_AP.toFixed(3)}</td><td>${fmt(m.precision)}</td><td>${fmt(m.recall)}</td><td>${m.flagged}</td><td>${m.fp}</td></tr>`).join('');
data.examples.forEach((x,i)=>{let o=document.createElement('option');o.value=i;o.textContent=x.account_id+' · '+x.example_type;el('account').append(o)});
function show(){const x=data.examples[Number(el('account').value)];if(!x)return;el('details').innerHTML=`<h3>${x.account_id}</h3><p>Model score: <strong>${x.score.toFixed(3)}</strong> · ${x.review_flag?'Review flag':'Below review threshold'} · fold ${x.outer_fold}</p><p><strong>Proposed hold amount: unavailable.</strong> ${x.reason}</p><h4>Exact interventional Shapley attribution</h4><p>Baseline ${x.baseline.toFixed(3)} plus contributions equals score ${x.score.toFixed(3)}. Background: ${x.background_size} training accounts. Contributions explain predictions, not culpability.</p><table><tr><th>Feature</th><th>Observed value</th><th>Contribution</th></tr>${x.contributions.map(c=>`<tr><td>${c.feature}</td><td>${c.value===null?'Missing / unavailable':c.value.toPrecision(4)}</td><td>${c.contribution>=0?'+':''}${c.contribution.toFixed(4)}</td></tr>`).join('')}</table><h4>Observed transfers (not established fraud evidence)</h4><div class="scroll"><table><tr><th>Reference</th><th>Sender → Receiver</th><th>Amount ₹</th><th>Time</th></tr>${x.transactions.map(t=>`<tr><td>${t.transaction_ref}</td><td>${t.sender_account} → ${t.receiver_account}</td><td>${t.amount.toFixed(2)}</td><td>${t.timestamp}</td></tr>`).join('')}</table></div>`};el('account').onchange=show;show();
el('download').onclick=()=>{const x=data.examples[Number(el('account').value)],b=new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=x.account_id+'_evidence.json';a.click();URL.revokeObjectURL(u)};
el('sensitivity').innerHTML=data.results.sensitivity.map(s=>`<p>${s.scenario}: mean score ${s.mean_score_before.toFixed(3)} → ${s.mean_score_after.toFixed(3)} (${s.accounts} accounts)</p>`).join('');</script></html>'''
    (out/'dashboard.html').write_text(html.replace('PAYLOAD',payload))
if __name__=='__main__':build(Path(__file__).resolve().parent/'reports')
